package common

var DefaultProblem = &ProblemDetails{}

// ProblemDetails conforms to RFC 7807 for representing API errors in a
// standardized and machine-readable format.
//
// Use this structure when returning detailed error responses to clients.
// It helps clients programmatically identify error types, status codes,
// and debugging information.
type ProblemDetails struct {
	// Type is a URI reference that identifies the problem type.
	// If not specified, "about:blank" is typically used.
	Type string `json:"type"`

	// Title is a short, human-readable summary of the problem type.
	// It should not change from occurrence to occurrence.
	Title string `json:"title"`

	// Status is the HTTP status code generated by the origin server.
	Status int `json:"status"`

	// Detail is a human-readable explanation specific to this occurrence of the problem.
	Detail string `json:"detail"`

	// Instance is a URI reference that identifies the specific occurrence of the problem.
	// It may or may not yield further information if dereferenced.
	Instance *string `json:"instance,omitempty"`
}
