name: Pre-Release

on:
  workflow_dispatch:
  workflow_run:

permissions:
  contents: write
  packages: read

jobs:
  TagAndPublish:
    name: Tag and Notify Go Proxy
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Checkout Full History
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v4.0.1

      - name: Calculate Version
        id: version
        uses: gittools/actions/gitversion/execute@v4.0.1
<<<<<<< HEAD
=======

      - name: Set Up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.24.0

      - name: Install Dependencies
        run: go mod tidy

      - name: Download Dependencies
        run: go mod download

      - name: Build Project
        run: go build ./...

      - name: Run Tests
        run: go test ./... -v -coverprofile=coverage.out
>>>>>>> aae1627c7c0d2d2ba04183299720335143544952

      - name: Tag Commit
        uses: fgrzl/actions/tag-commit@v0.0.3
        with:
          tag: ${{ steps.version.outputs.semVer }}

      - name: Notify Go Proxy
        uses: fgrzl/actions/notify-go-proxy@v0.0.3
        with:
          tag: ${{ steps.version.outputs.semVer }}

      - name: Prune Pre-release Tags
        uses: fgrzl/actions/prune-tags@v0.0.3
